from __future__ import annotations

from app.ai.contracts import AnalysisClip, AnalysisResult, AnalysisSegment


class MockVideoAnalyzer:
    provider = "mock"

    def analyze(self, source: dict, prompt: str, model: str) -> AnalysisResult:
        duration = float(source.get("duration_sec") or 0)
        if duration <= 0:
            duration = 60
        segment_count = 1 if duration < 45 else 3 if duration >= 90 else 2
        segments: list[AnalysisSegment] = []
        for index in range(segment_count):
            start = min(index * 25, max(duration - 10, 0))
            end = min(start + min(20, max(duration - start, 5)), duration)
            if end - start < 5:
                start = max(0, duration - 5)
                end = duration
            segments.append(
                AnalysisSegment(
                    start_sec=round(start, 3),
                    end_sec=round(end, 3),
                    title=f"Mock short #{index + 1}",
                    description="Candidate clip generated by mock analyzer.",
                    score=max(0.55, 0.9 - index * 0.12),
                    category="insight" if index == 0 else "reaction",
                    color="#2563EB" if index == 0 else "#7C3AED",
                    reason="Mock segment for pipeline testing without external AI calls.",
                )
            )
        if duration >= 90 and len(segments) >= 3:
            clips = [
                AnalysisClip(
                    title="Mock montage #1",
                    description="Two-part candidate clip generated by mock analyzer.",
                    score=0.92,
                    category="conflict",
                    color="#DC2626",
                    segments=[segments[0], segments[1]],
                ),
                AnalysisClip(
                    title=segments[2].title,
                    description=segments[2].description,
                    score=segments[2].score,
                    category=segments[2].category,
                    color=segments[2].color,
                    segments=[segments[2]],
                ),
            ]
        else:
            clips = [
                AnalysisClip(
                    title=segment.title,
                    description=segment.description,
                    score=segment.score,
                    category=segment.category,
                    color=segment.color,
                    segments=[segment],
                )
                for segment in segments
            ]
        return AnalysisResult(
            segments=segments,
            clips=clips,
            response={
                "provider": self.provider,
                "model": model,
                "prompt_chars": len(prompt),
                "clips": [
                    {
                        "title": clip.title,
                        "description": clip.description,
                        "score": clip.score,
                        "category": clip.category,
                        "color": clip.color,
                        "segments": [segment.to_store_dict() for segment in clip.segments],
                    }
                    for clip in clips
                ],
                "segments": [segment.to_store_dict() for segment in segments],
            },
            usage={"mock": True},
        )
