from __future__ import annotations

from app.ai.contracts import AnalysisResult, AnalysisSegment


class MockVideoAnalyzer:
    provider = "mock"

    def analyze(self, source: dict, prompt: str, model: str) -> AnalysisResult:
        duration = float(source.get("duration_sec") or 0)
        if duration <= 0:
            duration = 60
        segment_count = 1 if duration < 45 else 2
        segments: list[AnalysisSegment] = []
        for index in range(segment_count):
            start = min(index * 25, max(duration - 10, 0))
            end = min(start + min(20, max(duration - start, 5)), duration)
            if end - start < 5:
                start = max(0, duration - 5)
                end = duration
            segments.append(
                AnalysisSegment(
                    start_sec=round(start, 3),
                    end_sec=round(end, 3),
                    title=f"Mock short #{index + 1}",
                    description="Candidate clip generated by mock analyzer.",
                    score=max(0.55, 0.9 - index * 0.12),
                    category="insight" if index == 0 else "reaction",
                    color="#2563EB" if index == 0 else "#7C3AED",
                    reason="Mock segment for pipeline testing without external AI calls.",
                )
            )
        return AnalysisResult(
            segments=segments,
            response={
                "provider": self.provider,
                "model": model,
                "prompt_chars": len(prompt),
                "segments": [segment.to_store_dict() for segment in segments],
            },
            usage={"mock": True},
        )
